services: mongodb

sudo: false

language: ruby

cache: bundler

matrix:
  include:
    rvm:
      - 2.2
      - 2.1.1
      - 2.0.0
      - 1.9.3
      - rbx-2
      - jruby-19mode

    env:
      - MONGOID_VERSION=3
      - MONGOID_VERSION=4
      - MONGOID_VERSION=5
      - MONGOID_VERSION=3
        REQUEST_STORE_VERSION='~>1.3.1'
      - MONGOID_VERSION=4
        REQUEST_STORE_VERSION='~>1.3.1'
      - MONGOID_VERSION=5
        REQUEST_STORE_VERSION='~>1.3.1'

  allow_failures:
    - rvm: rbx-2
